### ISSUE TITLE
ESP32 board you used

### ISSUE THREAD

**Issue by lorenberg** [H-LK/ESP32_Arducam_Port#1]
Hello,

I just came across your repository, and it seems like you started a great project by making this port!
I have an arducam ov2640, and I would like to try your code....could you please tell me the exact model of ESP32 board you used, to be sure of being in the same conditions?
Thank you!

**Comment by H-LK** [comment]
Sorry for the late response.
I am using this board
http://www.gravitech.us/naiotdebo4mb.html

Other boards should work too.
